# 터미널에 명령어 자체가 출력되는 것을 방지하기 위해 @를 붙임

up:
	@./docker-compose-ctl.sh up

down:
	@./docker-compose-ctl.sh down

start:
	@./docker-compose-ctl.sh start

stop:
	@./docker-compose-ctl.sh stop

restart:
	@./docker-compose-ctl.sh restart

clean:
	@./docker-compose-ctl.sh clean

status:
	@./docker-compose-ctl.sh status